=== UNA-UNDERGROUND/programacionIV-Examen-1-2021/datos/info-spj.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="información">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lista-sorteos"/>
        <xs:element ref="lista-usuarios"/>
        <xs:element ref="lista-apuestas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="lista-sorteos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="sorteo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sorteo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="número-sorteo"/>
        <xs:element ref="fecha"/>
        <xs:element ref="motivo"/>
        <xs:element ref="retorno"/>
        <xs:element ref="número-ganador" minOccurs="0"/>
        <xs:element ref="estado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fecha" type="xs:date"/>
  <xs:element name="motivo" type="xs:string"/>
  <xs:element name="retorno">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minExclusive value="1"/>
        <xs:maxExclusive value="100"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="número-ganador">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="99"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="estado">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="3"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="lista-usuarios">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="usuario"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="usuario">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="cédula"/>
        <xs:element ref="clave"/>
        <xs:element ref="apellidos"/>
        <xs:element ref="nombre"/>
        <xs:element ref="tarjeta"/>
      </xs:choice>
      <xs:attribute name="administrador" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="apellidos" type="xs:string"/>
  <xs:element name="clave" type="xs:string"/>
  <xs:element name="nombre" type="xs:string"/>
  <xs:element name="tarjeta">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="tipo" type="xs:string"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="lista-apuestas">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="apuesta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="apuesta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cédula"/>
        <xs:element ref="número-sorteo"/>
        <xs:element ref="número-juego"/>
        <xs:element ref="monto-apuesta"/>
        <xs:element ref="monto-premio"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="número-juego">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="99"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="monto-apuesta" type="xs:integer"/>
  <xs:element name="monto-premio" type="xs:integer"/>
  <xs:element name="número-sorteo" type="xs:integer"/>
  <xs:element name="cédula" type="xs:string"/>
</xs:schema>

=== UNA-UNDERGROUND/programacionIV-Examen-1-2021/datos/info-spj.xml
<?xml version="1.0" encoding="UTF-8"?>
<información xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="info-spj.xsd">
    <lista-sorteos>
        <sorteo>
            <número-sorteo>26311</número-sorteo>
            <fecha>2021-04-26</fecha>
            <motivo>Día Mundial de la Propiedad Intelectual</motivo>
            <retorno>75</retorno>
            <número-ganador>75</número-ganador>
            <estado>3</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26312</número-sorteo>
            <fecha>2021-04-27</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <número-ganador>41</número-ganador>
            <estado>3</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26313</número-sorteo>
            <fecha>2021-04-28</fecha>
            <motivo>Día Mundial por la Seguridad y Salud en el Trabajo</motivo>
            <retorno>75</retorno>
            <número-ganador>47</número-ganador>
            <estado>3</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26314</número-sorteo>
            <fecha>2021-04-29</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <número-ganador>4</número-ganador>
            <estado>3</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26315</número-sorteo>
            <fecha>2021-04-30</fecha>
            <motivo>Día de Star Wars</motivo>
            <retorno>75</retorno>
            <número-ganador>91</número-ganador>
            <estado>3</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26316</número-sorteo>
            <fecha>2021-05-01</fecha>
            <motivo>Día Internacional del Trabajador</motivo>
            <retorno>75</retorno>
            <número-ganador>71</número-ganador>
            <estado>3</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26317</número-sorteo>
            <fecha>2021-05-02</fecha>
            <motivo>Día Mundial Contra el Bullying o el Acoso Escolar</motivo>
            <retorno>75</retorno>
            <número-ganador>22</número-ganador>
            <estado>3</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26318</número-sorteo>
            <fecha>2021-05-03</fecha>
            <motivo>Día de la Libertad de Prensa</motivo>
            <retorno>75</retorno>
            <número-ganador>91</número-ganador>
            <estado>3</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26319</número-sorteo>
            <fecha>2021-05-04</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <número-ganador>5</número-ganador>
            <estado>3</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26320</número-sorteo>
            <fecha>2021-05-05</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>2</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26321</número-sorteo>
            <fecha>2021-05-06</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>2</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26322</número-sorteo>
            <fecha>2021-05-07</fecha>
            <motivo>Día Internacional Del Taxista</motivo>
            <retorno>75</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26323</número-sorteo>
            <fecha>2021-05-08</fecha>
            <motivo>Día Mundial de la Cruz Roja</motivo>
            <retorno>75</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26324</número-sorteo>
            <fecha>2021-05-09</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26325</número-sorteo>
            <fecha>2021-05-10</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26326</número-sorteo>
            <fecha>2021-05-11</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26327</número-sorteo>
            <fecha>2021-05-12</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26328</número-sorteo>
            <fecha>2021-05-13</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26329</número-sorteo>
            <fecha>2021-05-14</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26330</número-sorteo>
            <fecha>2021-05-15</fecha>
            <motivo>Día Internacional de la Familia</motivo>
            <retorno>75</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26331</número-sorteo>
            <fecha>2021-05-16</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26332</número-sorteo>
            <fecha>2021-05-17</fecha>
            <motivo>Día Mundial del Reciclaje</motivo>
            <retorno>75</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26333</número-sorteo>
            <fecha>2021-05-18</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26334</número-sorteo>
            <fecha>2021-05-19</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26335</número-sorteo>
            <fecha>2021-05-20</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26336</número-sorteo>
            <fecha>2021-05-21</fecha>
            <motivo>Día Mundial de la Diversidad Cultural para el Diálogo y el Desarrollo</motivo>
            <retorno>75</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26337</número-sorteo>
            <fecha>2021-05-22</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26338</número-sorteo>
            <fecha>2021-05-23</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26339</número-sorteo>
            <fecha>2021-05-24</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26340</número-sorteo>
            <fecha>2021-05-25</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26341</número-sorteo>
            <fecha>2021-05-26</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26342</número-sorteo>
            <fecha>2021-05-27</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26343</número-sorteo>
            <fecha>2021-05-28</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26344</número-sorteo>
            <fecha>2021-05-29</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26345</número-sorteo>
            <fecha>2021-05-30</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26346</número-sorteo>
            <fecha>2021-05-31</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26347</número-sorteo>
            <fecha>2021-06-01</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26348</número-sorteo>
            <fecha>2021-06-02</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26349</número-sorteo>
            <fecha>2021-06-03</fecha>
            <motivo>Sorteo ordinario</motivo>
            <retorno>60</retorno>
            <estado>1</estado>
        </sorteo>
        <sorteo>
            <número-sorteo>26350</número-sorteo>
